### ISSUE TITLE
Adding activation functions

### ISSUE THREAD

**Issue by akgopan** [alpha-davidson/TensorBNN#3]
Hi
I would like to add an exponential activation function to this. Would it be ok if I were to add that to the activation code and push it here so it is available for everyone?

**Comment by brkronheim** [comment]
I've merged the pull request, though this new code won't be available through the pip install yet. If anyone wants to use this activation through the version on pip they can include the class declaration somewhere in the python file used for training:

class Exp(Layer):
    """Exponential activation function"""

    def __init__(self, inputDims=None, outputDims=None):
        self.numTensors = 0
        self.numHyperTensors = 0
        self.name = "Exp"

    def predict(self, inputTensor, _):
        result = tf.math.exp(inputTensor)
        return(result)

Once this is present, simply add the Exp layer like any other activation. To make predictions with it, include the class in the prediction code as well, and simply include the argument customLayerDict = {"Exp": Exp} when initializing the predictor object. This method can be used for any custom layers.
